### ISSUE TITLE
Notifaction title is "Python" instead of RocketType

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/rockettype#3]
![image](https://user-images.githubusercontent.com/1004314/91652317-6218ae00-ea96-11ea-95fa-3cd7144ce0aa.png)

We could try to have a proper .exe by:

1. using a different freezer/installer
2. seeing if pynsist offers to build to .exe >> it doesn't ("You don’t get an exe for your application, just a start menu shortcut to launch it.")
3. if this disappears if we use enty_point=module:function in pynsist (probably not as this is related to win10toast)
4. see if we can influence win10toast (probably not: https://github.com/jithurjacob/Windows-10-Toast-Notifications/issues/74)

I don't think we should fix this. I don't feel like switching the whole installer because of this ...

**Comment by appins** [comment]
This should naturally go away when an executable is being run and creates the notification.
