### ISSUE TITLE
Wrong/No notification icon

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/rockettype#4]
![image](https://user-images.githubusercontent.com/1004314/91652365-e10de680-ea96-11ea-9cd8-51cf6f89b7cc.png)

**Comment by appins** [comment]
The path isn't absolute, so perhaps this will have to be installed somewhere on the users computer. If you run `python logger.pyw` You should see the icon.

**Comment by appins** [comment]
Can you confirm that `icon.ico` exists? If so perhaps it's the wrong size/format.

**Comment by janmechtel** [comment]
Yes it exists. It actually works when I don't run debugging from VS Code

**Comment by appins** [comment]
Ahh, well, it should be noted that we should have it in the install folder at some point.
