### ISSUE TITLE
Storing log securely and/or avoid storing passwords

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/rockettype#6]
Find a way to not store passwords.

Currently we require the user to disable recording. And remember to turn it back on ...

Instead we could:

- **Don't store the letter** when running with pythonw.exe, only store it with python.exe

- Encrypt the .txt with a password? Windows User Account > makes stats harder
- Avoid logging passwords - Idea: Have a regular expression filter that stops recording for n-chars if the beginning of the password is matched?) - Have to understand the key before and after + needs to delay logging or purge from log

- Santize: - don't store all the text,  opportuniyt bs,bs ty
- More efficient logging & stats (Ideas: one file per day?  sqlite)
- having it be sorted at the end of each day, when paused, and/or when the program is exited. That way if a hacker gets into someone's computer only today's data / data since a few minutes ago is readable and we're not sorting a giant file every time a user presses a key.

**Comment by appins** [comment]
We should revisit this when logging what keys and not just words/min
